language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
after_script:
  - mvn test jacoco:report coveralls:report -Dcoveralls.token=$coveralls_repo_token

matrix:
  allow_failures:
  - jdk: oraclejdk8
